/**
 * PageIndex response interfaces for Python integration.
 *
 * These interfaces map the output format of the PageIndex library
 * to TypeScript types for type-safe communication between NestJS and Python.
 *
 * @see Issue #1552 - [PI-1538c] Implementar TreeBuilderService com integração Python
 * @see https://github.com/VectifyAI/PageIndex
 */

/**
 * A node in the PageIndex document structure.
 * Represents a section, chapter, or article in the document hierarchy.
 */
export interface PageIndexNode {
  /** Unique identifier for this node */
  node_id: string;

  /** Title or heading of this section */
  title: string;

  /** Starting page number (1-indexed) */
  start_index: number;

  /** Ending page number (1-indexed) */
  end_index: number;

  /** Optional summary generated by LLM */
  summary?: string;

  /** Optional full text content of this section */
  text?: string;

  /** Child nodes (subsections) */
  nodes: PageIndexNode[];
}

/**
 * Complete response from PageIndex document processing.
 */
export interface PageIndexResponse {
  /** Original document name */
  doc_name: string;

  /** Generated document description */
  doc_description?: string;

  /** Hierarchical structure of the document */
  structure: PageIndexNode[];

  /** Processing metadata */
  metadata?: {
    /** Total number of pages processed */
    page_count?: number;

    /** Model used for processing */
    model?: string;

    /** Processing time in seconds */
    processing_time_seconds?: number;

    /** Total number of nodes in the tree */
    node_count?: number;

    /** Maximum depth of the tree */
    max_depth?: number;

    /** Whether this was a fallback parse (no PageIndex) */
    fallback?: boolean;
  };
}

/**
 * Error response from PageIndex processing.
 */
export interface PageIndexError {
  /** Error type identifier */
  error_type: 'PROCESSING_ERROR' | 'INVALID_INPUT' | 'MODEL_ERROR' | 'TIMEOUT';

  /** Human-readable error message */
  message: string;

  /** Additional error details */
  details?: Record<string, unknown>;
}

/**
 * Options for PageIndex document processing.
 */
export interface PageIndexOptions {
  /** Model to use for processing (default: gpt-4o-2024-11-20) */
  model?: string;

  /** Number of pages to check for table of contents (default: 20) */
  toc_check_page_num?: number;

  /** Maximum pages per node (default: 10) */
  max_page_num_each_node?: number;

  /** Maximum tokens per node (default: 20000) */
  max_token_num_each_node?: number;

  /** Whether to add node IDs (default: yes) */
  if_add_node_id?: 'yes' | 'no';

  /** Whether to add node summaries (default: yes) */
  if_add_node_summary?: 'yes' | 'no';

  /** Whether to add document description (default: yes) */
  if_add_doc_description?: 'yes' | 'no';

  /** Whether to add full text to nodes (default: no) */
  if_add_node_text?: 'yes' | 'no';
}

/**
 * Health check response from Python script.
 */
export interface PageIndexHealthResponse {
  /** Status indicator */
  status: string;

  /** Whether PageIndex library is installed */
  pageindex_available: boolean;

  /** Python version string */
  python_version: string;
}

/**
 * Union type for Python script responses.
 */
export type PageIndexResult =
  | { success: true; data: PageIndexResponse | PageIndexHealthResponse }
  | { success: false; error: PageIndexError };
